# Generated by Django 2.0.5 on 2018-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('ipython', models.FileField(blank=True, null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=120)),
                ('likes', models.IntegerField(default=0)),
                ('post_comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('big', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('draft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
